#!/usr/bin/env python3
"""Generate include/secrets.h from the config and the device logins.

Token values are written only to the header (mode 0600) and never printed.
deploy_and_build.sh deletes the header, and the compiled objects that embed
it, as soon as the build finishes.

    gen_secrets.py --config ~/.config/claude-status/config.toml --out include/secrets.h
    gen_secrets.py --config ... --out ... --placeholder   # dummy tokens, compile checks
"""
import argparse, hashlib, json, os, sys, time
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config as cfgmod


def plan_name(o):
    sub  = (o.get("subscriptionType") or "").lower()
    tier = (o.get("rateLimitTier") or "").lower()
    if sub == "max":
        for mult in ("20x", "5x"):
            if mult in tier:
                return f"MAX {mult}"
        return "MAX"
    return sub.upper() or "?"


def system_tz():
    # The last line of a TZif file is its POSIX rule, e.g. CST6CDT,M3.2.0,M11.1.0
    try:
        with open(os.path.realpath("/etc/localtime"), "rb") as f:
            rule = f.read().splitlines()[-1].decode()
        if rule and (rule[0].isalpha() or rule[0] == "<"):
            return rule
    except (OSError, IndexError, UnicodeDecodeError):
        pass
    return "UTC0"


def c_str(s):
    # JSON escaping is valid C++ for these strings (\uXXXX included).
    return json.dumps(s)


def when(ms):
    return datetime.fromtimestamp(ms / 1000, timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def die(msg):
    sys.exit(f"xx {msg}")


def read_login(cfg, acct, now_ms):
    alias, email = acct["alias"], acct["email"]
    d = cfgmod.login_dir(cfg, alias)
    creds = os.path.join(d, ".credentials.json")
    try:
        o = json.load(open(creds))["claudeAiOauth"]
    except FileNotFoundError:
        die(f"no device login for '{alias}'. Run: ./login.sh {alias}")
    except (OSError, KeyError, ValueError) as e:
        die(f"can't read the device login for '{alias}' ({creds}): {e}")
    for k in ("accessToken", "refreshToken"):
        if not o.get(k):
            die(f"device login for '{alias}' has no {k}. Run: ./login.sh {alias}")

    # login.sh records the account it verified; refuse a mismatch with config.
    try:
        verified = open(os.path.join(d, "verified-email")).read().strip()
    except OSError:
        die(f"device login for '{alias}' was never verified. Run: ./login.sh {alias}")
    if verified.lower() != email.lower():
        die(f"'{alias}' is logged in as {verified}, but config says {email}. Run: ./login.sh {alias}")

    rexp = o.get("refreshTokenExpiresAt")
    note = f", refresh token good until {when(rexp)}" if rexp else ""
    print(f"   {alias:<16} {plan_name(o):<8} {email}{note}", file=sys.stderr)
    return o


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--placeholder", action="store_true",
                    help="write dummy tokens (compile checks without logins)")
    a = ap.parse_args()

    try:
        cfg = cfgmod.load(a.config)
    except cfgmod.ConfigError as e:
        die(str(e))

    now_ms = int(time.time() * 1000)
    rows = []
    for acct in cfg["accounts"]:
        if a.placeholder:
            o = {"accessToken": "placeholder", "refreshToken": "placeholder",
                 "expiresAt": 0, "scopes": ["user:profile"], "subscriptionType": "pro"}
        else:
            o = read_login(cfg, acct, now_ms)
        rows.append({
            "label":   acct["alias"],
            "plan":    plan_name(o),
            "scope":   cfg["refresh_scope"] or " ".join(o.get("scopes") or []),
            "models":  ",".join(acct["models"]),
            # Identifies the login without revealing it. The device reseeds an
            # account's tokens only when this changes, i.e. after ./login.sh.
            "seed":    hashlib.sha256(o["refreshToken"].encode()).hexdigest()[:16],
            "access":  o["accessToken"],
            "refresh": o["refreshToken"],
            "expires": int(o.get("expiresAt") or 0),
        })

    arr = lambda key, fmt=c_str: "{ " + ", ".join(fmt(r[key]) for r in rows) + " }"
    body = f"""// GENERATED by tools/gen_secrets.py - never commit. Holds OAuth tokens and WiFi credentials.
#pragma once
#include <stdint.h>

#define WIFI_SSID        {c_str(cfg["ssid"])}
#define WIFI_PASS        {c_str(cfg["password"])}
#define DEVICE_HOSTNAME  {c_str(cfg["hostname"])}
#define OAUTH_CLIENT_ID  {c_str(cfg["client_id"])}
#define TZ_POSIX         {c_str(cfg["timezone"] or system_tz())}
#define PAGE_SECONDS     {cfg["page_seconds"]}

#define ACCOUNT_COUNT {len(rows)}
static const char* const ACCT_LABEL[]      = {arr("label")};
static const char* const ACCT_PLAN[]       = {arr("plan")};
static const char* const ACCT_SCOPE[]      = {arr("scope")};
static const char* const ACCT_MODELS[]     = {arr("models")};
static const char* const ACCT_SEED[]       = {arr("seed")};
static const char* const ACCT_ACCESS[]     = {arr("access")};
static const char* const ACCT_REFRESH[]    = {arr("refresh")};
static const uint64_t    ACCT_EXPIRES_MS[] = {arr("expires", lambda e: f"{e}ULL")};
"""
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    fd = os.open(a.out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(body)
    os.chmod(a.out, 0o600)
    print(f"   device '{cfg['hostname']}' on WiFi '{cfg['ssid']}', "
          f"refresh scope '{cfg['refresh_scope'] or 'full'}'", file=sys.stderr)


if __name__ == "__main__":
    main()
