#!/usr/bin/env python3
"""Rasterize a single-path SVG into anti-aliased 8-bit alpha maps for the TFT.

Pure Python, no dependencies: parses the path (M/L/H/V/C/Z, absolute and
relative), flattens the curves, and fills with non-zero winding at 4x4
supersampling. Writes a C header with one alpha map per requested size.
"""
import re, sys

def parse_path(d):
    toks = re.findall(r"[MmLlHhVvCcZz]|-?(?:\d+\.?\d*|\.\d+)(?:e-?\d+)?", d)
    polys, cur, i = [], [], 0
    x = y = sx = sy = 0.0
    cmd = None
    def num():
        nonlocal i
        v = float(toks[i]); i += 1; return v
    while i < len(toks):
        if re.match(r"[A-Za-z]", toks[i]):
            cmd = toks[i]; i += 1
            if cmd in "Zz":
                if cur: polys.append(cur); cur = []
                x, y = sx, sy
                continue
        rel = cmd.islower()
        c = cmd.upper()
        if c == "M":
            nx, ny = num(), num()
            if rel: nx += x; ny += y
            if cur: polys.append(cur)
            cur = [(nx, ny)]; x, y = sx, sy = nx, ny
            cmd = "l" if rel else "L"        # further pairs are implicit lines
        elif c == "L":
            nx, ny = num(), num()
            if rel: nx += x; ny += y
            x, y = nx, ny; cur.append((x, y))
        elif c == "H":
            nx = num(); x = x + nx if rel else nx; cur.append((x, y))
        elif c == "V":
            ny = num(); y = y + ny if rel else ny; cur.append((x, y))
        elif c == "C":
            p = [num() for _ in range(6)]
            if rel: p = [p[k] + (x if k % 2 == 0 else y) for k in range(6)]
            x0, y0 = x, y
            for s in range(1, 13):
                t = s / 12; u = 1 - t
                bx = u**3*x0 + 3*u*u*t*p[0] + 3*u*t*t*p[2] + t**3*p[4]
                by = u**3*y0 + 3*u*u*t*p[1] + 3*u*t*t*p[3] + t**3*p[5]
                cur.append((bx, by))
            x, y = p[4], p[5]
        else:
            raise ValueError(f"unsupported path command {cmd}")
    if cur: polys.append(cur)
    return polys

def inside(polys, px, py):
    wind = 0
    for poly in polys:
        n = len(poly)
        for k in range(n):
            (x1, y1), (x2, y2) = poly[k], poly[(k + 1) % n]
            if y1 <= py < y2 or y2 <= py < y1:
                xi = x1 + (py - y1) * (x2 - x1) / (y2 - y1)
                if xi > px: wind += 1 if y2 > y1 else -1
    return wind != 0

def rasterize(polys, size, view=100.0, ss=4):
    out = []
    for r in range(size):
        for c in range(size):
            hits = 0
            for sy in range(ss):
                for sx in range(ss):
                    px = (c + (sx + 0.5) / ss) * view / size
                    py = (r + (sy + 0.5) / ss) * view / size
                    hits += inside(polys, px, py)
            out.append(round(255 * hits / (ss * ss)))
    return out

def main():
    svg, header, *sizes = sys.argv[1:]
    d = re.search(r'\bd="([^"]+)"', open(svg).read()).group(1)
    polys = parse_path(d)
    lines = ["// GENERATED by tools/svg_to_alpha.py from assets/claude-mark.svg.",
             "// 8-bit coverage maps: blend the mark color over the background by alpha.",
             "#pragma once", "#include <stdint.h>", ""]
    for s in map(int, sizes):
        a = rasterize(polys, s)
        lines.append(f"#define CLAUDE_MARK_{s} {s}")
        lines.append(f"static const uint8_t CLAUDE_MARK_{s}_ALPHA[{s * s}] = {{")
        for r in range(s):
            lines.append("  " + ",".join(f"{v:3d}" for v in a[r*s:(r+1)*s]) + ",")
        lines.append("};")
        lines.append("")
        # Coarse preview so the result can be eyeballed in a terminal.
        if s <= 24:
            print(f"--- {s}x{s} ---", file=sys.stderr)
            for r in range(s):
                print("".join(" .:-=+*#%@"[min(9, v * 10 // 256)] for v in a[r*s:(r+1)*s]), file=sys.stderr)
    open(header, "w").write("\n".join(lines) + "\n")

if __name__ == "__main__":
    main()
